# -*- coding: utf-8 -*-
"""titanic_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t7kcUFa6pcalkE9i7u-nQVUsUi7u-4N0
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

df = pd.read_csv('train.csv')
print("Shape:", df.shape)
df.head()

# ============================================
# COMPLETE EDA CODE - Titanic Dataset
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
df = pd.read_csv('train.csv')

# ===== 1. DATA OVERVIEW =====
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nFirst 5 rows:\n", df.head())
print("\nData types:\n", df.dtypes)

# ===== 2. MISSING VALUES =====
print("\nMissing values:\n", df.isnull().sum())

# Handle missing
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df = df.drop('Cabin', axis=1)

# ===== 3. STATISTICS =====
print("\nStatistical summary:\n", df.describe())

# ===== 4. UNIVARIATE PLOTS =====
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

sns.countplot(x='Survived', data=df, ax=axes[0,0])
axes[0,0].set_title('Survival Count')

sns.histplot(df['Age'], bins=30, kde=True, ax=axes[0,1])
axes[0,1].set_title('Age Distribution')

sns.countplot(x='Pclass', data=df, ax=axes[1,0])
axes[1,0].set_title('Passenger Class')

sns.histplot(df['Fare'], bins=50, ax=axes[1,1])
axes[1,1].set_title('Fare Distribution')

plt.tight_layout()
plt.show()

# ===== 5. BIVARIATE PLOTS =====
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

sns.countplot(x='Sex', hue='Survived', data=df, ax=axes[0,0])
axes[0,0].set_title('Survival by Gender')

sns.countplot(x='Pclass', hue='Survived', data=df, ax=axes[0,1])
axes[0,1].set_title('Survival by Class')

sns.boxplot(x='Survived', y='Age', data=df, ax=axes[1,0])
axes[1,0].set_title('Age vs Survival')

sns.boxplot(x='Survived', y='Fare', data=df, ax=axes[1,1])
axes[1,1].set_title('Fare vs Survival')

plt.tight_layout()
plt.show()

# ===== 6. CORRELATION HEATMAP =====
numeric_cols = df.select_dtypes(include=[np.number]).columns
plt.figure(figsize=(8,6))
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# ===== 7. KEY INSIGHTS =====
print("\n" + "="*50)
print("KEY INSIGHTS")
print("="*50)
print(f"Overall survival rate: {df['Survived'].mean()*100:.1f}%")
print(f"\nSurvival by gender:")
print(df.groupby('Sex')['Survived'].mean())
print(f"\nSurvival by class:")
print(df.groupby('Pclass')['Survived'].mean())